// ============================================
// DADOS ESTÁTICOS DOS EVENTOS — MAANDHOO CLUB
// Atualize via painel admin em produção
// ============================================

import { Evento } from '@/types'

export const EVENTOS_INICIAIS: Evento[] = [
  {
    id: 'evt-001',
    slug: 'me-leva-pro-pagode-07-mar',
    nome: 'Me Leva Pro Pagode',
    data: new Date('2025-03-07'),
    hora: '22:00',
    descricao: 'Destak do Samba (DDS) + Pagode + Funk. Com DJ Gustavo Wippel e Rafa Freitas.',
    flyerUrl: '/images/flyers/Flyer_Me_Leva_Pro_Pagode_07MAR.webp',
    status: 'publicado',
    temLista: true,
    limiteListaMasc: 200,
    limiteListaFem: 200,
    prazoLista: new Date('2025-03-07T00:00:00'),
    lotes: [
      {
        id: 'lote-001-1',
        eventoId: 'evt-001',
        numero: 1,
        nome: '1º Lote',
        precoMasculino: 30,
        precoFeminino: 15,
        qtdMasculino: 100,
        qtdFeminino: 100,
        vendidoMasculino: 100,
        vendidoFeminino: 100,
        ativo: false,
        ordem: 1,
      },
      {
        id: 'lote-001-2',
        eventoId: 'evt-001',
        numero: 2,
        nome: '2º Lote',
        precoMasculino: 40,
        precoFeminino: 20,
        qtdMasculino: 150,
        qtdFeminino: 150,
        vendidoMasculino: 150,
        vendidoFeminino: 150,
        ativo: false,
        ordem: 2,
      },
      {
        id: 'lote-001-3',
        eventoId: 'evt-001',
        numero: 3,
        nome: '3º Lote',
        precoMasculino: 50,
        precoFeminino: 20,
        qtdMasculino: 200,
        qtdFeminino: 200,
        vendidoMasculino: 0,
        vendidoFeminino: 0,
        ativo: true,
        ordem: 3,
      },
    ],
    criadoEm: new Date('2025-02-15'),
    atualizadoEm: new Date('2025-02-15'),
  },
  {
    id: 'evt-002',
    slug: 'fluxou-14-mar',
    nome: 'Fluxou',
    data: new Date('2025-03-14'),
    hora: '23:00',
    descricao: 'Dreysson Rodrigues + Kaué Sousa + DJ Gustavo Wippel. A noite que vai fluir.',
    flyerUrl: '/images/flyers/Flyer_Fluxou_14MAR.webp',
    status: 'publicado',
    temLista: true,
    limiteListaMasc: 200,
    limiteListaFem: 200,
    prazoLista: new Date('2025-03-14T00:00:00'),
    lotes: [
      {
        id: 'lote-002-1',
        eventoId: 'evt-002',
        numero: 1,
        nome: '1º Lote',
        precoMasculino: 30,
        precoFeminino: 15,
        qtdMasculino: 100,
        qtdFeminino: 100,
        vendidoMasculino: 100,
        vendidoFeminino: 100,
        ativo: false,
        ordem: 1,
      },
      {
        id: 'lote-002-2',
        eventoId: 'evt-002',
        numero: 2,
        nome: '2º Lote',
        precoMasculino: 40,
        precoFeminino: 20,
        qtdMasculino: 150,
        qtdFeminino: 150,
        vendidoMasculino: 120,
        vendidoFeminino: 130,
        ativo: false,
        ordem: 2,
      },
      {
        id: 'lote-002-3',
        eventoId: 'evt-002',
        numero: 3,
        nome: '3º Lote',
        precoMasculino: 50,
        precoFeminino: 20,
        qtdMasculino: 200,
        qtdFeminino: 200,
        vendidoMasculino: 0,
        vendidoFeminino: 0,
        ativo: true,
        ordem: 3,
      },
    ],
    criadoEm: new Date('2025-02-20'),
    atualizadoEm: new Date('2025-02-20'),
  },
  {
    id: 'evt-003',
    slug: 'dj-narru-21-mar',
    nome: 'DJ Narru',
    data: new Date('2025-03-21'),
    hora: '23:00',
    descricao: 'DJ Narru + Grupo Sem Abuso. Pagode + Funk na maior casa de BC.',
    flyerUrl: '/images/flyers/Flyer_DJ_NARRU_21MAR.webp',
    status: 'publicado',
    temLista: true,
    limiteListaMasc: 200,
    limiteListaFem: 200,
    prazoLista: new Date('2025-03-21T00:00:00'),
    lotes: [
      {
        id: 'lote-003-1',
        eventoId: 'evt-003',
        numero: 1,
        nome: '1º Lote',
        precoMasculino: 30,
        precoFeminino: 15,
        qtdMasculino: 100,
        qtdFeminino: 100,
        vendidoMasculino: 100,
        vendidoFeminino: 100,
        ativo: false,
        ordem: 1,
      },
      {
        id: 'lote-003-2',
        eventoId: 'evt-003',
        numero: 2,
        nome: '2º Lote',
        precoMasculino: 40,
        precoFeminino: 20,
        qtdMasculino: 150,
        qtdFeminino: 150,
        vendidoMasculino: 50,
        vendidoFeminino: 70,
        ativo: false,
        ordem: 2,
      },
      {
        id: 'lote-003-3',
        eventoId: 'evt-003',
        numero: 3,
        nome: '3º Lote',
        precoMasculino: 50,
        precoFeminino: 20,
        qtdMasculino: 200,
        qtdFeminino: 200,
        vendidoMasculino: 0,
        vendidoFeminino: 0,
        ativo: true,
        ordem: 3,
      },
    ],
    criadoEm: new Date('2025-02-25'),
    atualizadoEm: new Date('2025-02-25'),
  },
]

export const getLoteAtivo = (evento: Evento) => {
  return evento.lotes.find(l => l.ativo) || evento.lotes[evento.lotes.length - 1]
}

export const getPrecoMinimo = (evento: Evento) => {
  const lote = getLoteAtivo(evento)
  return Math.min(lote.precoMasculino, lote.precoFeminino)
}
